// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gnosispay_sync.Database;

#nullable disable

namespace gnosispay_sync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gnosispay_sync.Data.Transactions.CardTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BillingAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_amount");

                    b.Property<string>("BillingCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("billing_currency");

                    b.Property<short>("BillingDecimals")
                        .HasColumnType("smallint")
                        .HasColumnName("billing_decimals");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<bool>("IsPending")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pending");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Mcc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mcc");

                    b.Property<string>("MerchantCity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_city");

                    b.Property<string>("MerchantCountry")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("merchant_country");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_name");

                    b.Property<string>("OnchainTxHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("onchain_tx_hash");

                    b.Property<long?>("RefundAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("refund_amount");

                    b.Property<string>("RefundCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("refund_currency");

                    b.Property<long?>("ReversalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("reversal_amount");

                    b.Property<string>("ReversalCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reversal_currency");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("thread_id");

                    b.Property<long>("TransactionAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_amount");

                    b.Property<string>("TransactionCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("transaction_currency");

                    b.Property<short>("TransactionDecimals")
                        .HasColumnType("smallint")
                        .HasColumnName("transaction_decimals");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_card_transactions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_card_transactions_created_at");

                    b.HasIndex("Mcc")
                        .HasDatabaseName("ix_card_transactions_mcc");

                    b.HasIndex("MerchantCountry")
                        .HasDatabaseName("ix_card_transactions_merchant_country");

                    b.HasIndex("IsPending", "ClearedAt")
                        .HasDatabaseName("ix_card_transactions_is_pending_cleared_at");

                    b.HasIndex("ThreadId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_card_transactions_thread_id_kind");

                    b.ToTable("card_transactions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
